spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/url_shortener
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    static-path-pattern: /static/**

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace